import turtle
storona_kletki = 50
storona_kletki_diagonal = 20
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(180)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki * 2)
turtle.left(90)
turtle.forward(storona_kletki * 2)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki * 2)
turtle.right(45)
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(45)
turtle.forward(storona_kletki * 3)
turtle.right(135)
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(180)
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(135)
turtle.forward(storona_kletki * 3)
turtle.right(45)
turtle.forward(storona_kletki_diagonal * 3)
turtle.done()