import turtle

storona_kletki = 100
storona_kletki_diagonal = 50

turtle.penup()
turtle.goto(-200, 100)
turtle.pendown()
turtle.pensize(2)

# Передняя грань
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.end_fill()
# Клетки передней грани
turtle.right(90)
turtle.forward(storona_kletki)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.left(90)
turtle.forward(storona_kletki * 2)
turtle.left(90)
turtle.forward(storona_kletki)
turtle.left(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki)
turtle.right(90)
turtle.forward(storona_kletki * 3)
turtle.right(90)
turtle.forward(storona_kletki * 2)

# Верхняя грань
turtle.right(45)
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(45)
turtle.forward(storona_kletki * 3)
turtle.right(135)
turtle.forward(storona_kletki_diagonal * 3)
turtle.end_fill()
# Клетки верхней грани
turtle.right(45)
turtle.forward(storona_kletki)
turtle.right(135)
turtle.forward(storona_kletki_diagonal * 3)
turtle.left(135)
turtle.forward(storona_kletki)
turtle.left(45)
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(45)
turtle.forward(storona_kletki)
turtle.right(135)
turtle.forward(storona_kletki_diagonal)
turtle.right(45)
turtle.forward(storona_kletki * 3)
turtle.left(45)
turtle.forward(storona_kletki_diagonal)
turtle.left(135)
turtle.forward(storona_kletki * 3)
turtle.backward(storona_kletki * 3)
turtle.left(45)
turtle.forward(storona_kletki_diagonal * 2)

# Правая грань
turtle.right(180)
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.forward(storona_kletki_diagonal * 3)
turtle.right(135)
turtle.forward(storona_kletki * 3)
turtle.right(45)
turtle.forward(storona_kletki_diagonal * 3)
turtle.end_fill()
# Клетки правой грани
turtle.right(135)
turtle.forward(storona_kletki * 3)
turtle.right(45)
turtle.forward(storona_kletki_diagonal)
turtle.right(135)
turtle.forward(storona_kletki * 3)
turtle.left(135)
turtle.forward(storona_kletki_diagonal)
turtle.left(45)
turtle.forward(storona_kletki * 3)
turtle.right(45)
turtle.forward(storona_kletki_diagonal)
turtle.right(135)
turtle.forward(storona_kletki)
turtle.right(45)
turtle.forward(storona_kletki_diagonal * 3)
turtle.left(45)
turtle.forward(storona_kletki)
turtle.left(135)
turtle.forward(storona_kletki_diagonal * 3)

turtle.done()
